In [4]:
from pathlib import Path
import pandas as pd

project_root = next(folder for folder in (Path.cwd(), *Path.cwd().parents) if (folder / "src" / "pronostico_geomagnetico").is_dir())
path = project_root / "data" / "raw" / "omni2_1990.dat"
df = pd.read_csv(path, sep=r"\s+", header=None)

In [5]:
df.shape

(8760, 55)

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,1990,1,0,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,0.5,-40,14,99.9
1,1990,1,1,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,0.1,-33,11,99.9
2,1990,1,2,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,-0.0,-19,16,99.9
3,1990,1,3,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,15,209.3,0.1,-26,39,99.9
4,1990,1,4,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,15,209.3,0.6,-73,79,99.9

In [7]:
COLUMN_NAMES = [
    "year",
    "day_of_year",
    "hour",
    "bartels_rotation",
    "imf_spacecraft_id",
    "plasma_spacecraft_id",
    "imf_sample_count",
    "plasma_sample_count",
    "b_magnitude_mean_nt",
    "b_vector_magnitude_nt",
    "b_latitude_gse_deg",
    "b_longitude_gse_deg",
    "bx_gse_nt",
    "by_gse_nt",
    "bz_gse_nt",
    "by_gsm_nt",
    "bz_gsm_nt",
    "sigma_b_magnitude_nt",
    "sigma_b_vector_nt",
    "sigma_bx_gse_nt",
    "sigma_by_gse_nt",
    "sigma_bz_gse_nt",
    "proton_temperature_k",
    "proton_density_cm3",
    "solar_wind_speed_kms",
    "flow_longitude_deg",
    "flow_latitude_deg",
    "alpha_proton_ratio",
    "flow_pressure_npa",
    "sigma_proton_temperature_k",
    "sigma_proton_density_cm3",
    "sigma_solar_wind_speed_kms",
    "sigma_flow_longitude_deg",
    "sigma_flow_latitude_deg",
    "sigma_alpha_proton_ratio",
    "electric_field_mvm",
    "plasma_beta",
    "alfven_mach_number",
    "kp_x10",
    "sunspot_number",
    "dst_nt",
    "ae_nt",
    "proton_flux_gt_1mev",
    "proton_flux_gt_2mev",
    "proton_flux_gt_4mev",
    "proton_flux_gt_10mev",
    "proton_flux_gt_30mev",
    "proton_flux_gt_60mev",
    "magnetospheric_flux_flag",
    "ap_nt",
    "f107_sfu",
    "pcn",
    "al_nt",
    "au_nt",
    "magnetosonic_mach_number",
]

In [8]:
df.columns = column_names

NameError: name 'column_names' is not defined

In [ ]:
df.head()

,year,day_of_year,hour,bartels_rotation,imf_spacecraft_id,plasma_spacecraft_id,imf_sample_count,plasma_sample_count,b_magnitude_mean_nt,b_vector_magnitude_nt,...,proton_flux_gt_10mev,proton_flux_gt_30mev,proton_flux_gt_60mev,magnetospheric_flux_flag,ap_nt,f107_sfu,pcn,al_nt,au_nt,magnetosonic_mach_number
0,1990,1,0,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,0.5,-40,14,99.9
1,1990,1,1,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,0.1,-33,11,99.9
2,1990,1,2,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,7,209.3,-0.0,-19,16,99.9
3,1990,1,3,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,15,209.3,0.1,-26,39,99.9
4,1990,1,4,2136,99,99,999,999,999.9,999.9,...,99999.99,99999.99,99999.99,0,15,209.3,0.6,-73,79,99.9

In [10]:
def load_omni(path: Path) -> pd.DataFrame:
    """Lee un archivo horario de OMNI y asigna nombres a sus columnas."""
    df = pd.read_csv(path, sep=r"\s+", header=None)
    df.columns = COLUMN_NAMES
    return df

In [11]:
df = load_omni(path)

In [12]:
df.shape

(8760, 55)

In [13]:
def load_omni(path: Path) -> pd.DataFrame:
    
    if not path.is_file():
    # Lanzar una excepción que explique qué archivo falta.
        raise FileNotFoundError(f"No existe el archivo: {path}")
    
    """Lee un archivo horario de OMNI y asigna nombres a sus columnas."""
    df = pd.read_csv(path, sep=r"\s+", header=None)
    df.columns = COLUMN_NAMES
    
    return df

In [14]:
load_omni(Path("archivo_inexistente.dat"))

FileNotFoundError: No existe el archivo: archivo_inexistente.dat

In [15]:
horas_validas = df["hour"].between(0, 23)
horas_validas.value_counts()

hour
True    8760
Name: count, dtype: int64

UnboundLocalError: cannot access local variable 'df' where it is not associated with a value

In [16]:
from pathlib import Path
import sys

import pandas as pd

# Localizar el proyecto desde la ra?z o desde la carpeta del notebook.
project_root = next(
    folder for folder in (Path.cwd(), *Path.cwd().parents)
    if (folder / "src" / "pronostico_geomagnetico" / "exceptions.py").is_file()
)
if str(project_root / "src") not in sys.path:
    sys.path.insert(0, str(project_root / "src"))

from pronostico_geomagnetico.exceptions import OmniLoadError

path = project_root / "data" / "raw" / "omni2_1990.dat"

COLUMN_NAMES = [
    "year",
    "day_of_year",
    "hour",
    "bartels_rotation",
    "imf_spacecraft_id",
    "plasma_spacecraft_id",
    "imf_sample_count",
    "plasma_sample_count",
    "b_magnitude_mean_nt",
    "b_vector_magnitude_nt",
    "b_latitude_gse_deg",
    "b_longitude_gse_deg",
    "bx_gse_nt",
    "by_gse_nt",
    "bz_gse_nt",
    "by_gsm_nt",
    "bz_gsm_nt",
    "sigma_b_magnitude_nt",
    "sigma_b_vector_nt",
    "sigma_bx_gse_nt",
    "sigma_by_gse_nt",
    "sigma_bz_gse_nt",
    "proton_temperature_k",
    "proton_density_cm3",
    "solar_wind_speed_kms",
    "flow_longitude_deg",
    "flow_latitude_deg",
    "alpha_proton_ratio",
    "flow_pressure_npa",
    "sigma_proton_temperature_k",
    "sigma_proton_density_cm3",
    "sigma_solar_wind_speed_kms",
    "sigma_flow_longitude_deg",
    "sigma_flow_latitude_deg",
    "sigma_alpha_proton_ratio",
    "electric_field_mvm",
    "plasma_beta",
    "alfven_mach_number",
    "kp_x10",
    "sunspot_number",
    "dst_nt",
    "ae_nt",
    "proton_flux_gt_1mev",
    "proton_flux_gt_2mev",
    "proton_flux_gt_4mev",
    "proton_flux_gt_10mev",
    "proton_flux_gt_30mev",
    "proton_flux_gt_60mev",
    "magnetospheric_flux_flag",
    "ap_nt",
    "f107_sfu",
    "pcn",
    "al_nt",
    "au_nt",
    "magnetosonic_mach_number",
]


def load_omni(path: Path) -> pd.DataFrame:
    """Lee un archivo horario de OMNI y asigna nombres a sus columnas."""

    # Comprobar que el archivo existe.
    if not path.is_file():
        raise OmniLoadError(f"No existe el archivo: {path}")

    # Leer el archivo y tratar el caso de archivo vacío.
    try:
        df = pd.read_csv(path, sep=r"\s+", header=None)
    except pd.errors.EmptyDataError as error:
        raise OmniLoadError(f"El archivo está vacío: {path}") from error

    # Comprobar la cantidad de columnas antes de nombrarlas.
    if df.shape[1] != len(COLUMN_NAMES):
        raise OmniLoadError(
            f"Se esperaban {len(COLUMN_NAMES)} columnas, "
            f"pero el archivo contiene {df.shape[1]}"
        )

    df.columns = COLUMN_NAMES
    return df


# Preparar df para las comprobaciones de las ?ltimas celdas.
df = load_omni(path)

In [17]:
try:
    load_omni(Path("archivo_inexistente.dat"))
except OmniLoadError as error:
    print(error)

No existe el archivo: archivo_inexistente.dat

In [18]:
import pytest

In [19]:
df.shape

(8760, 55)

In [20]:
from tempfile import TemporaryDirectory #crear un arvhivo temporal vacio

with TemporaryDirectory() as folder:
    empty_path = Path(folder) / "vacio.dat"
    empty_path.touch()

    try:
        load_omni(empty_path)
    except OmniLoadError as error:
        print(error)

El archivo está vacío: C:\Users\alvar\AppData\Local\Temp\tmp0skbh39g\vacio.dat

In [21]:
horas_validas = df["hour"].between(0, 23)
horas_validas.value_counts()

hour
True    8760
Name: count, dtype: int64

In [22]:
df.columns

Index(['year', 'day_of_year', 'hour', 'bartels_rotation', 'imf_spacecraft_id',
       'plasma_spacecraft_id', 'imf_sample_count', 'plasma_sample_count',
       'b_magnitude_mean_nt', 'b_vector_magnitude_nt', 'b_latitude_gse_deg',
       'b_longitude_gse_deg', 'bx_gse_nt', 'by_gse_nt', 'bz_gse_nt',
       'by_gsm_nt', 'bz_gsm_nt', 'sigma_b_magnitude_nt', 'sigma_b_vector_nt',
       'sigma_bx_gse_nt', 'sigma_by_gse_nt', 'sigma_bz_gse_nt',
       'proton_temperature_k', 'proton_density_cm3', 'solar_wind_speed_kms',
       'flow_longitude_deg', 'flow_latitude_deg', 'alpha_proton_ratio',
       'flow_pressure_npa', 'sigma_proton_temperature_k',
       'sigma_proton_density_cm3', 'sigma_solar_wind_speed_kms',
       'sigma_flow_longitude_deg', 'sigma_flow_latitude_deg',
       'sigma_alpha_proton_ratio', 'electric_field_mvm', 'plasma_beta',
       'alfven_mach_number', 'kp_x10', 'sunspot_number', 'dst_nt', 'ae_nt',
       'proton_flux_gt_1mev', 'proton_flux_gt_2mev', 'proton_flux_gt_4mev',
       'proton_flux_gt_10mev', 'proton_flux_gt_30mev', 'proton_flux_gt_60mev',
       'magnetospheric_flux_flag', 'ap_nt', 'f107_sfu', 'pcn', 'al_nt',
       'au_nt', 'magnetosonic_mach_number'],
      dtype='str')

In [23]:
MIN_HOUR = 0
MAX_HOUR = 23

In [30]:
from exceptions import OmniValidationError

In [32]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que las horas sean enteras y estén entre 0 y 23."""
    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

In [34]:
prueba_val = validate_omni(pd.DataFrame({"hour": [0, 12, 23]}))
print (prueba_val)

None

In [35]:
validate_omni(pd.DataFrame({"hour": [24]}))

OmniValidationError: La hora debe estar entre 0 y 23

In [36]:
validate_omni(pd.DataFrame({"hour": [12.5]}))

OmniValidationError: La hora debe ser un número entero

In [ ]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que las horas sean enteras y estén entre 0 y 23."""
    if df["hour"].isna().any():
        raise OmniValidationError("La hora no puede contener valores vacios")

    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

In [40]:
validate_omni(pd.DataFrame({"hour": [0, None, 23]}))

OmniValidationError: La hora no puede contener valores ausentes

In [42]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que el año y la hora tengan valores numéricos enteros."""
    # Validar el año.
    if df["year"].isna().any():
        raise OmniValidationError(
            "El año no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["year"]):
        raise OmniValidationError(
            "El año debe contener valores numéricos"
        )

    if (df["year"] % 1 != 0).any():
        raise OmniValidationError("El año debe ser un número entero")

    # Validar la hora.
    if df["hour"].isna().any():
        raise OmniValidationError(
            "La hora no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["hour"]):
        raise OmniValidationError(
            "La hora debe contener valores numéricos"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )
    if (~df["day_of_year"].between(1, 366)).any():
        raise OmniValidationError("El día del año debe estar entre 1 y 366")

In [43]:
validate_omni(
    pd.DataFrame({"year": [1990], "day_of_year": [1], "hour": [12]})
)

In [44]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que el año y la hora tengan valores numéricos enteros."""
    # Validar el año.
    if df["year"].isna().any():
        raise OmniValidationError(
            "El año no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["year"]):
        raise OmniValidationError(
            "El año debe contener valores numéricos"
        )

    if (df["year"] % 1 != 0).any():
        raise OmniValidationError("El año debe ser un número entero")

    # Validar la hora.
    if df["hour"].isna().any():
        raise OmniValidationError(
            "La hora no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["hour"]):
        raise OmniValidationError(
            "La hora debe contener valores numéricos"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )
    if (~df["day_of_year"].between(1, 366)).any():
        raise OmniValidationError("El día del año debe estar entre 1 y 366")
    bisiesto = (
    (df["year"] % 4 == 0)
    & ((df["year"] % 100 != 0) | (df["year"] % 400 == 0))
)

    if ((df["day_of_year"] == 366) & ~bisiesto).any():
        raise OmniValidationError(
            "El día 366 solo es válido en años bisiestos"
        )

In [45]:
validate_omni(
    pd.DataFrame({"year": [1992], "day_of_year": [366], "hour": [12]})
)

In [46]:
# Debe lanzar el error: 1990 tiene 365 días.
validate_omni(
    pd.DataFrame({"year": [1990], "day_of_year": [366], "hour": [12]})
)

OmniValidationError: El día 366 solo es válido en años bisiestos

In [48]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que el año y la hora tengan valores numéricos enteros."""
    # Validar el año.
    if df["year"].isna().any():
        raise OmniValidationError(
            "El año no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["year"]):
        raise OmniValidationError(
            "El año debe contener valores numéricos"
        )

    if (df["year"] % 1 != 0).any():
        raise OmniValidationError("El año debe ser un número entero")

    # Validar la hora.
    if df["hour"].isna().any():
        raise OmniValidationError(
            "La hora no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["hour"]):
        raise OmniValidationError(
            "La hora debe contener valores numéricos"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )
    if (~df["day_of_year"].between(1, 366)).any():
        raise OmniValidationError("El día del año debe estar entre 1 y 366")
    bisiesto = ((
        df["year"] % 4 == 0)
        & ((df["year"] % 100 != 0) 
        | (df["year"] % 400 == 0))
)

    if ((df["day_of_year"] == 366) & ~bisiesto).any():
        raise OmniValidationError(
            "El día 366 solo es válido en años bisiestos"
        )
    if df.duplicated(subset=["year", "day_of_year", "hour"]).any():
        raise OmniValidationError(
        "Hay registros duplicados para el mismo año, día y hora"
    )

In [51]:
df_prueba_duplicados = pd.DataFrame({
    "year": [1990, 1990],
    "day_of_year": [1, 1],
    "hour": [12, 12],
})

validate_omni(df_prueba_duplicados)

OmniValidationError: Hay registros duplicados para el mismo año, día y hora

In [54]:
def validate_omni(df: pd.DataFrame) -> None:
    """Comprueba que el año y la hora tengan valores numéricos enteros."""
   
    columnas_necesarias = ["year", "day_of_year", "hour"]

    for columna in columnas_necesarias:
        if columna not in df.columns:
            raise OmniValidationError(
                f"Falta la columna obligatoria: {columna}"
            )
        
    # Validar el año.
    if df["year"].isna().any():
        raise OmniValidationError(
            "El año no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["year"]):
        raise OmniValidationError(
            "El año debe contener valores numéricos"
        )

    if (df["year"] % 1 != 0).any():
        raise OmniValidationError("El año debe ser un número entero")

    # Validar la hora.
    if df["hour"].isna().any():
        raise OmniValidationError(
            "La hora no puede contener valores ausentes"
        )

    if not pd.api.types.is_numeric_dtype(df["hour"]):
        raise OmniValidationError(
            "La hora debe contener valores numéricos"
        )

    if (df["hour"] % 1 != 0).any():
        raise OmniValidationError("La hora debe ser un número entero")

    if (~df["hour"].between(MIN_HOUR, MAX_HOUR)).any():
        raise OmniValidationError(
            f"La hora debe estar entre {MIN_HOUR} y {MAX_HOUR}"
        )
    if (~df["day_of_year"].between(1, 366)).any():
        raise OmniValidationError("El día del año debe estar entre 1 y 366")
    bisiesto = ((
        df["year"] % 4 == 0)
        & ((df["year"] % 100 != 0) 
        | (df["year"] % 400 == 0))
)

    if ((df["day_of_year"] == 366) & ~bisiesto).any():
        raise OmniValidationError(
            "El día 366 solo es válido en años bisiestos"
        )
    if df.duplicated(subset=["year", "day_of_year", "hour"]).any():
        raise OmniValidationError(
        "Hay registros duplicados para el mismo año, día y hora"
    )

In [55]:
validate_omni(pd.DataFrame({"year": [1990], "hour": [12]}))

OmniValidationError: Falta la columna obligatoria: day_of_year

In [61]:
fill_values = {
    "bz_gsm_nt": 999.9,
    "proton_density_cm3": 999.9,
    "solar_wind_speed_kms": 9999.0,
    "kp_x10": 99,
}

df_clean = df.copy()

for columna, codigo in fill_values.items():
    df_clean[columna] = df_clean[columna].replace(codigo, float("nan"))

In [62]:
df_clean[list(fill_values)].isna().sum()

bz_gsm_nt               5072
proton_density_cm3      5157
solar_wind_speed_kms    5157
kp_x10                     0
dtype: int64

In [65]:
df_2000 = load_omni((project_root / "data" / "raw" / "omni2_2000.dat"))
validate_omni(df_2000)

df_2000_clean = df_2000.copy()

for columna, codigo in fill_values.items():
    df_2000_clean[columna] = df_2000_clean[columna].replace(
        codigo, float("nan")
    )

completas_2000 = df_2000_clean[list(fill_values)].notna().all(axis=1)

print("Total de filas:", len(df_2000_clean))
print("Filas completas:", completas_2000.sum())
print("Porcentaje:", completas_2000.mean() * 100)

Total de filas: 8784
Filas completas: 8017
Porcentaje: 91.26821493624773

In [66]:
grupos_2000 = completas_2000.ne(completas_2000.shift()).cumsum()

huecos_2000 = (
    (~completas_2000)[~completas_2000]
    .groupby(grupos_2000[~completas_2000])
    .size()
)

print("Número de huecos:", len(huecos_2000))
print("Hueco más largo (horas):", huecos_2000.max())
print("Los cinco huecos más largos:")
print(huecos_2000.nlargest(5))

Número de huecos: 31
Hueco más largo (horas): 104
Los cinco huecos más largos:
12    104
30     91
22     70
18     69
20     51
dtype: int64

In [67]:
import pandas as pd


def calculate_metrics(df: pd.DataFrame) -> dict:
    """Calcula la disponibilidad de las variables seleccionadas."""
    columnas = [
        "bz_gsm_nt",
        "proton_density_cm3",
        "solar_wind_speed_kms",
        "kp_x10",
    ]

    completas = df[columnas].notna().all(axis=1)
    total = len(df)

    return {
        "total_filas": total,
        "filas_completas": int(completas.sum()),
        "filas_incompletas": int((~completas).sum()),
        "porcentaje_completas": (
            float(completas.mean() * 100) if total > 0 else 0.0
        ),
    }

In [68]:
print (calculate_metrics(df))

{'total_filas': 8760, 'filas_completas': 8760, 'filas_incompletas': 0, 'porcentaje_completas': 100.0}

In [69]:
print("1990:", calculate_metrics(df_clean))
print("2000:", calculate_metrics(df_2000_clean))

1990: {'total_filas': 8760, 'filas_completas': 3528, 'filas_incompletas': 5232, 'porcentaje_completas': 40.273972602739725}
2000: {'total_filas': 8784, 'filas_completas': 8017, 'filas_incompletas': 767, 'porcentaje_completas': 91.26821493624773}

In [71]:
from pronostico_geomagnetico.preprocessor import preprocess_omni

df = load_omni((project_root / "data" / "raw" / "omni2_2000.dat"))
validate_omni(df)
df_clean = preprocess_omni(df)

calculate_metrics(df_clean)

{'total_filas': 8784,
 'filas_completas': 8017,
 'filas_incompletas': 767,
 'porcentaje_completas': 91.26821493624773}